### ISSUE TITLE
Feature request: Open only when dragging

### ISSUE THREAD

**Issue by M0ebiu5** [ngdeleito/easyGestures#3]
Could you please implement the feature from the old version: "open only when dragging"?

I use easy gestures with the right button and without that feature, it interferes with the normal context menu.

**Comment by ngdeleito** [comment]
Thanks for your comment.

I removed long time ago the "open only when dragging" feature because it was buggy and I saw at that time little value in trying to fix it. I might though reconsider my decision in the future, once the extension reaches again a more complete state.

In the meantime, I suggest you to use the "prevent pie menu from opening with key" feature to let the context menu appear in place of the pie menu.

Hope this helps,
Nicolas
